# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks

# Setup
title:            tazz0009
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://tazz0009.github.io/
baseurl:          /

author:
  name:           'tazz0009'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tazz009/
