# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            tazz0009
tagline:          'TECH'
description:      'TECH'
url:              https://tazz0009.github.io/
baseurl:          /

author:
  name:           'tazz0009'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tazz0009/
